### ISSUE TITLE
Number Format Exception 

### ISSUE THREAD

**Issue by bpowell461** [bpowell461/SHA-2#1]
Whenever  input is a multiple of 4. For example:

`java SHATest abcd`

`Exception in thread "main" java.lang.NumberFormatException: For input string: "10000000000000000000000000000000"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at SHA2.parseMessage(SHA2.java:70)
        at SHA2.<init>(SHA2.java:38)
        at SHATest.main(SHATest.java:4)`

**Comment by bpowell461** [comment]
Using Big Integer to correct the error will alter the algorithm, SHA-256 uses unsigned integers only. Since Java does not have unsigned integers, I just used signed integers.

**Comment by bpowell461** [comment]
Each 512 bit chunk is broke up into 16 blocks of 32-bit words. When the input is a length multiple of 4, one of the blocks parsed will be 2^31 in binary. This value exceeds Integer.MAX_VALUE. I believe I am missing something in the algorithm itself to correct this error

**Comment by bpowell461** [comment]
Issue was resolved by changing parse value to long then casting other values to ints
